### ISSUE TITLE
Credentials are not reflected correctly after changing them

### ISSUE THREAD

**Issue by oelick** [qlik-oss/qlik-cloud-entitlement-analyzer#31] opened 2024-06-11 00:12 UTC
## 🐛 Bug report

Hi.
Deploy the EntitlementAnalyzer app in your tenant to see how your users are using it.
Among them, there is a problem that when the user's credentials are changed (from AnalyzerCapacity to professional), the changed credentials are not reflected.
*Not reflected for some users.

### Steps to Reproduce

1. change someone's entitlement.
2. Check the entitlementAnalyzer(Do Reload)

### Expected behavior
I expect any of the following to change.
1 Entitlement_Assigned
2 Consumed Entitlement
3 Current entitlement
4 Entitlement
5 Entitlement_Consumed

### Actual behavior
None of them will change

### Additional context
[Question 1]
If you know why this happens and how to make it happen, please let me know.

[Question 2]
The items referred to as credentials are:
I would like to know the difference between them.
1 Entitlement_Assigned
2 Consumed Entitlement
3 Current entitlement
4 Entitlement
5 Entitlement_Consumed

Credentials are not correctly reflected for
usersFor 2 and 5, analyzer_time information is included, but professional information is not reflected, and all 5 items above are displayed as [-].

Question 3:
If you look at the audience data according to the data model,
the 1:Entitlement_Assigned table exists with a TenantUserKey of 1, but all other items are
[-]2:TenantMetadata There is no record associated with the target user in the table Entitlement_Assigned and the
TenantID of the target user in the table is [-], so it is not linked to TenantMetadata.
I understand that, but does this mean that the data is an outlier?

**Comment by danielpilla** [comment] 2024-06-11 02:54
Hi @oelick,
Firstly, make sure you are on the latest version of the app.

I just gave this a test and am not able to reproduce your issue.

**Scenario 1 Steps:**
- Current user has Professional entitlement and is shown in the app as such
- Change user to Analyzer entitlement
- Reload the app
- Change is reflected in the app

**Scenario 2 Steps:**
- Current user has no license but has used analyzer capacity minutes in the past
- Change user to Professional entitlement
- Reload the app
- Change is reflected in the app

You want to use the following dimensions:
- `Assigned user` - this is the user to which the entitlement was assigned (there is actually a typo in this field name, will be fixed)
- `Assigned Entitlement` - this is the entitlement to which the user was assigned
- `AssignedDate` - this is the date on which the entitlement was assigned
- `CurrentAssigneeType` - this is the current entitlement that the user has assigned

You mention the consumption fields as well, those are from the session logs. E.g., a user could have had been assigned a Professional entitlement, used an app, and then later been assigned an Analyzer entitlement and used an app. It is a slowly changing dimension.

In addition, there are also entitlement fields that are related to the current tenant license, so it really depends on what you're after.

Lastly, you mention analyzer capacity minutes. If a user uses analyzer capacity minutes, they technically do not have an entitlement and therefore would not be entered into the entitlements table until they explicitly assigned an entitlement.

I hope this helps-
Cheers,

**Comment by danielpilla** [comment] 2024-06-11 02:55
Closing as WAD

**Closed by danielpilla** 2024-06-11 02:55 UTC
