### ISSUE TITLE
Entitlement analyzer failing on the schedule after 1st setup

### ISSUE THREAD

**Issue by jenilsangoi** [qlik-oss/qlik-cloud-entitlement-analyzer#23] opened 2024-03-01 11:46 UTC
## 🐛 Bug report

(A clear and concise description of what the bug is.)

### Steps to Reproduce

1. setup entitlement analyzer
2. setup connection with timeout of 10000
3. Run the schedule
4. Schedule is failing.
5.
### Expected behavior

Get an output on Entitlement Analyzer

### Actual behavior

We have setup entitlement analyzer in our environment for 1st time and it is hitting 3 hours of the timeout and failing. The maximum time out that we can set it 10000.

I have also user optional configuration to get data only for 1 day with variable SET vu_initial_days_back = 1;

RestConnectorMasterTable << RestConnectorMasterTable
failed to complete reload: Failure: Request aborted (15 GENERIC ABORTED)
The following error occurred:
User abort (Reload canceled due to exceeding maximum duration)
### Additional context

(Add any other context, link to demo or screenshots about the issue.)

<img width="524" alt="image" src="https://github.com/qlik-oss/qlik-cloud-entitlement-analyzer/assets/161836024/1614c124-1adf-4c22-bb69-b55572087bc2">

**Comment by danielpilla** [comment] 2024-03-01 16:03
Hi @jenilsangoi,
I cannot reproduce this behavior. Given your description, it sounds like the app was installed manually. Could you please try installing and reloading using the [Qlik Application Automation Installer](https://community.qlik.com/t5/Official-Support-Articles/Qlik-Cloud-Monitoring-Apps-Workflow-Guide/ta-p/2134140)?

**Comment by jenilsangoi** [comment] 2024-03-01 16:20
Hi Daniel - Thank you for response. Yes we manually created the connection and application in my personal workspace. Let me check on the link you have shared.

**Comment by danielpilla** [comment] 2024-03-01 16:26
In addition and as an FYI, there is a bug in the installer automation where it will fail if the user has been individually assigned lesser privileges than the installer requires: `Can edit` on Shared and `Can publish` and `Can manage` on Managed are what is required. This has been resolved in the newest version, but it has not been pushed yet. Just in case you hit an error on the install, this is the only known issue currently.

**Comment by danielpilla** [comment] 2024-03-06 18:49
Hi @jenilsangoi,
Is this issue resolved?

**Comment by jenilsangoi** [comment] 2024-03-07 09:44
Hi @danielpilla,

Yes the issue has resolved. I have not published in managed space but did it for personal workspace and can see issue has been resolved.

**Comment by withdave** [comment] 2024-05-15 09:32
Closing as resolved.

**Closed by withdave** 2024-05-15 09:32 UTC
